export const PATCH_CACHE_DURATION = 300
export const PATCH_INTRODUCTION_CACHE_DURATION = 300
export const PATCH_FAVORITE_CACHE_DURATION = 60
export const HOME_CACHE_DURATION = 60
export const MARKDOWN_HTML_CACHE_DURATION = 30 * 24 * 60 * 60
